### ISSUE TITLE
Removing 2 consecutive elements from a list returns incorrect updates

### ISSUE THREAD

**Issue by mikkomultanen** [knaeckeKami/diffutil.dart#15]
```
    expect(
      calculateListDiff([1, 0, 2, 0, 3], [1, 0, 3], detectMoves: false).getUpdates().toList(),
      [const Remove(position: 2, count: 2)],
    );
```
Expected: [Remove:Remove{position: 2, count: 2}]
  Actual: [Remove:Remove{position: 3, count: 1}, Remove:Remove{position: 1, count: 1}]

**Comment by knaeckeKami** [comment]
Thank you for the bug report! 

It think like I re-implemented a bug from the Android source code when porting. https://issuetracker.google.com/issues/123376278

If this is the actual issue, it is related to duplicated items in a list. 

Will try to fix it, unfortunately it looks like the fix was to essentially re-implement to algorithm from scratch.
